// Auto-generated by tools/encoding/generate_encoding_data.py -- DO NOT EDIT.
// Regenerate with: python3 tools/encoding/generate_encoding_data.py
// Data: the Python standard library's codecs.

// clang-format off

#pragma once

#include <array>

namespace odr::internal::encoding::encoding_data {

/// Byte -> code point for one single-byte encoding; U+FFFD where the
/// encoding leaves the byte undefined.
using SingleByteTable = std::array<char32_t, 256>;

extern const SingleByteTable ibm866;
extern const SingleByteTable iso_8859_1;
extern const SingleByteTable iso_8859_2;
extern const SingleByteTable iso_8859_3;
extern const SingleByteTable iso_8859_4;
extern const SingleByteTable iso_8859_5;
extern const SingleByteTable iso_8859_6;
extern const SingleByteTable iso_8859_7;
extern const SingleByteTable iso_8859_8;
extern const SingleByteTable iso_8859_10;
extern const SingleByteTable iso_8859_13;
extern const SingleByteTable iso_8859_14;
extern const SingleByteTable iso_8859_15;
extern const SingleByteTable iso_8859_16;
extern const SingleByteTable koi8_r;
extern const SingleByteTable koi8_u;
extern const SingleByteTable macintosh;
extern const SingleByteTable windows_874;
extern const SingleByteTable windows_1250;
extern const SingleByteTable windows_1251;
extern const SingleByteTable windows_1252;
extern const SingleByteTable windows_1253;
extern const SingleByteTable windows_1254;
extern const SingleByteTable windows_1255;
extern const SingleByteTable windows_1256;
extern const SingleByteTable windows_1257;
extern const SingleByteTable windows_1258;
extern const SingleByteTable x_mac_cyrillic;

} // namespace odr::internal::encoding::encoding_data
