#!/usr/bin/env python3
"""Generate the simple-font encoding tables and Adobe Glyph List for the PDF
module.

The output is committed C++ source (``pdf_encoding_data.{hpp,cpp}``); the build
only compiles it, so there is no build-time dependency on this script. Re-run it
whenever the source data changes:

    python3 tools/pdf/generate_encoding_data.py

All source data is vendored next to this script as ``.txt`` files and read with
no command-line toggles, so regeneration is deterministic:

  * ``glyphlist.txt`` -- Adobe's Adobe Glyph List
    (https://github.com/adobe-type-tools/agl-aglfn, BSD-3-Clause). Lines are
    ``glyphname;CCCC CCCC`` (one or more hex UTF-16 code points). Names that
    follow the algorithmic ``uniXXXX`` / ``uXXXXXX`` forms are resolved at
    runtime and are not listed.
  * ``{standard,win_ansi,mac_roman}_encoding.txt`` -- the 256-entry base
    encodings (ISO 32000-1 / PDF 1.7, Annex D). Lines are ``HH;glyphname``;
    codes not listed map to .notdef.

All four share the same on-disk convention: ``#`` comment lines, blank lines
ignored, and two semicolon-delimited fields per record (see ``iter_records``).
"""

from __future__ import annotations

import argparse
import os
from collections.abc import Iterator

_DATA_DIR = os.path.dirname(os.path.abspath(__file__))
_ENCODING_NAMES = ("standard_encoding", "win_ansi_encoding", "mac_roman_encoding")


# --- Loading ----------------------------------------------------------------


def iter_records(path: str) -> Iterator[tuple[str, str]]:
    """Yield ``(field0, field1)`` for each record in a vendored data file.

    Skips ``#`` comments and blank lines; splits on the first ``;``.
    """
    with open(path, encoding="ascii") as handle:
        for line in handle:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            field0, sep, field1 = line.partition(";")
            assert sep, f"{path}: missing ';' in {line!r}"
            yield field0, field1


def load_base_encoding(path: str) -> list[str]:
    """Parse a base encoding (``HH;glyphname``) into a 256-entry table."""
    table = [""] * 256
    for code_hex, glyph in iter_records(path):
        table[int(code_hex, 16)] = glyph
    return table


def load_agl(path: str) -> dict[str, list[int]]:
    """Parse Adobe ``glyphlist.txt`` (``name;CCCC CCCC``)."""
    agl: dict[str, list[int]] = {}
    for name, codes in iter_records(path):
        agl[name] = [int(code, 16) for code in codes.split()]
    return agl


# --- Emit -------------------------------------------------------------------

_AUTOGEN = (
    "// Auto-generated by tools/pdf/generate_encoding_data.py -- DO NOT EDIT.\n"
    "// Regenerate after editing the vendored data files next to the script;\n"
    "// see the script header.\n"
    "\n"
    "// clang-format off"
)


def _cpp_u16(code_points: list[int]) -> str:
    return 'u"' + "".join(f"\\u{cp:04X}" for cp in code_points) + '"'


def emit_hpp(agl_size: int) -> str:
    out = [
        _AUTOGEN,
        "",
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstddef>",
        "#include <string_view>",
        "#include <utility>",
        "",
        "namespace odr::internal::pdf::encoding_data {",
        "",
        f"inline constexpr std::size_t adobe_glyph_list_size = {agl_size};",
        "",
    ]
    for name in _ENCODING_NAMES:
        out.append(f"extern const std::array<std::string_view, 256> {name};")
    out += [
        "",
        "extern const std::array<std::pair<std::string_view, std::u16string_view>,",
        "                        adobe_glyph_list_size>",
        "    adobe_glyph_list;",
        "",
        "} // namespace odr::internal::pdf::encoding_data",
        "",
    ]
    return "\n".join(out)


def emit_cpp(bases: dict[str, list[str]], agl: dict[str, list[int]]) -> tuple[str, int]:
    out = [
        _AUTOGEN,
        "",
        "#include <odr/internal/pdf/pdf_encoding_data.hpp>",
        "",
        "namespace odr::internal::pdf {",
        "",
    ]

    for table_name in _ENCODING_NAMES:
        mapping = bases[table_name]
        out.append(
            f"const std::array<std::string_view, 256> encoding_data::{table_name} = {{{{"
        )
        for code in range(256):
            glyph = mapping[code]
            out.append(f'    "{glyph}", // 0x{code:02X}')
        out += ["}};", ""]

    entries = sorted(agl.items())
    for name, _ in entries:
        assert ";" not in name and '"' not in name, name
    out.append("const std::array<std::pair<std::string_view, std::u16string_view>,")
    out.append("           encoding_data::adobe_glyph_list_size>")
    out.append("    encoding_data::adobe_glyph_list = {{")
    for name, code_points in entries:
        out.append(f'    {{"{name}", {_cpp_u16(code_points)}}},')
    out += ["}};", "", "} // namespace odr::internal::pdf", ""]
    return "\n".join(out), len(entries)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        default=os.path.join("src", "odr", "internal", "pdf"),
        help="output directory for pdf_encoding_data.{hpp,cpp}",
    )
    args = parser.parse_args()

    bases = {
        name: load_base_encoding(os.path.join(_DATA_DIR, f"{name}.txt"))
        for name in _ENCODING_NAMES
    }
    for name, table in bases.items():
        assert len(table) == 256, (name, len(table))
    agl = load_agl(os.path.join(_DATA_DIR, "glyphlist.txt"))

    cpp, count = emit_cpp(bases, agl)
    hpp = emit_hpp(count)

    os.makedirs(args.out, exist_ok=True)
    with open(os.path.join(args.out, "pdf_encoding_data.hpp"), "w") as handle:
        handle.write(hpp)
    with open(os.path.join(args.out, "pdf_encoding_data.cpp"), "w") as handle:
        handle.write(cpp)

    print(f"generated pdf_encoding_data.{{hpp,cpp}} ({count} AGL entries)")


if __name__ == "__main__":
    main()
