// Auto-generated by tools/font/generate_cff_standard_strings.py -- DO NOT EDIT.
// Regenerate by rerunning the script; see its header for the source data.
// CFF Standard Strings: Adobe Technical Note #5176, Appendix A.

// clang-format off


#pragma once

#include <array>
#include <cstddef>
#include <string_view>

namespace odr::internal::font::cff {

inline constexpr std::size_t cff_standard_strings_size = 391;

extern const std::array<std::string_view, cff_standard_strings_size>
    cff_standard_strings;

} // namespace odr::internal::font::cff
