########### AGGREGATED COMPONENTS AND DEPENDENCIES FOR THE MULTI CONFIG #####################
#############################################################################################

list(APPEND gtest_COMPONENT_NAMES GTest::gtest GTest::gtest_main GTest::gmock GTest::gmock_main)
list(REMOVE_DUPLICATES gtest_COMPONENT_NAMES)
if(DEFINED gtest_FIND_DEPENDENCY_NAMES)
  list(APPEND gtest_FIND_DEPENDENCY_NAMES )
  list(REMOVE_DUPLICATES gtest_FIND_DEPENDENCY_NAMES)
else()
  set(gtest_FIND_DEPENDENCY_NAMES )
endif()

########### VARIABLES #######################################################################
#############################################################################################
set(gtest_PACKAGE_FOLDER_RELWITHDEBINFO "/Users/andreas/.conan2/p/b/gtestb6bb409d34b28/p")
set(gtest_BUILD_MODULES_PATHS_RELWITHDEBINFO )


set(gtest_INCLUDE_DIRS_RELWITHDEBINFO "${gtest_PACKAGE_FOLDER_RELWITHDEBINFO}/include")
set(gtest_RES_DIRS_RELWITHDEBINFO )
set(gtest_DEFINITIONS_RELWITHDEBINFO )
set(gtest_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(gtest_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(gtest_OBJECTS_RELWITHDEBINFO )
set(gtest_COMPILE_DEFINITIONS_RELWITHDEBINFO )
set(gtest_COMPILE_OPTIONS_C_RELWITHDEBINFO )
set(gtest_COMPILE_OPTIONS_CXX_RELWITHDEBINFO )
set(gtest_LIB_DIRS_RELWITHDEBINFO "${gtest_PACKAGE_FOLDER_RELWITHDEBINFO}/lib")
set(gtest_BIN_DIRS_RELWITHDEBINFO )
set(gtest_LIBRARY_TYPE_RELWITHDEBINFO STATIC)
set(gtest_IS_HOST_WINDOWS_RELWITHDEBINFO 0)
set(gtest_LIBS_RELWITHDEBINFO gmock_main gmock gtest_main gtest)
set(gtest_SYSTEM_LIBS_RELWITHDEBINFO )
set(gtest_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(gtest_FRAMEWORKS_RELWITHDEBINFO )
set(gtest_BUILD_DIRS_RELWITHDEBINFO )
set(gtest_NO_SONAME_MODE_RELWITHDEBINFO FALSE)


# COMPOUND VARIABLES
set(gtest_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${gtest_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${gtest_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")
set(gtest_LINKER_FLAGS_RELWITHDEBINFO
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${gtest_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${gtest_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${gtest_EXE_LINK_FLAGS_RELWITHDEBINFO}>")


set(gtest_COMPONENTS_RELWITHDEBINFO GTest::gtest GTest::gtest_main GTest::gmock GTest::gmock_main)
########### COMPONENT GTest::gmock_main VARIABLES ############################################

set(gtest_GTest_gmock_main_INCLUDE_DIRS_RELWITHDEBINFO "${gtest_PACKAGE_FOLDER_RELWITHDEBINFO}/include")
set(gtest_GTest_gmock_main_LIB_DIRS_RELWITHDEBINFO "${gtest_PACKAGE_FOLDER_RELWITHDEBINFO}/lib")
set(gtest_GTest_gmock_main_BIN_DIRS_RELWITHDEBINFO )
set(gtest_GTest_gmock_main_LIBRARY_TYPE_RELWITHDEBINFO STATIC)
set(gtest_GTest_gmock_main_IS_HOST_WINDOWS_RELWITHDEBINFO 0)
set(gtest_GTest_gmock_main_RES_DIRS_RELWITHDEBINFO )
set(gtest_GTest_gmock_main_DEFINITIONS_RELWITHDEBINFO )
set(gtest_GTest_gmock_main_OBJECTS_RELWITHDEBINFO )
set(gtest_GTest_gmock_main_COMPILE_DEFINITIONS_RELWITHDEBINFO )
set(gtest_GTest_gmock_main_COMPILE_OPTIONS_C_RELWITHDEBINFO "")
set(gtest_GTest_gmock_main_COMPILE_OPTIONS_CXX_RELWITHDEBINFO "")
set(gtest_GTest_gmock_main_LIBS_RELWITHDEBINFO gmock_main)
set(gtest_GTest_gmock_main_SYSTEM_LIBS_RELWITHDEBINFO )
set(gtest_GTest_gmock_main_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(gtest_GTest_gmock_main_FRAMEWORKS_RELWITHDEBINFO )
set(gtest_GTest_gmock_main_DEPENDENCIES_RELWITHDEBINFO GTest::gmock)
set(gtest_GTest_gmock_main_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(gtest_GTest_gmock_main_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(gtest_GTest_gmock_main_NO_SONAME_MODE_RELWITHDEBINFO FALSE)

# COMPOUND VARIABLES
set(gtest_GTest_gmock_main_LINKER_FLAGS_RELWITHDEBINFO
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${gtest_GTest_gmock_main_SHARED_LINK_FLAGS_RELWITHDEBINFO}>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${gtest_GTest_gmock_main_SHARED_LINK_FLAGS_RELWITHDEBINFO}>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${gtest_GTest_gmock_main_EXE_LINK_FLAGS_RELWITHDEBINFO}>
)
set(gtest_GTest_gmock_main_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${gtest_GTest_gmock_main_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${gtest_GTest_gmock_main_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")
########### COMPONENT GTest::gmock VARIABLES ############################################

set(gtest_GTest_gmock_INCLUDE_DIRS_RELWITHDEBINFO "${gtest_PACKAGE_FOLDER_RELWITHDEBINFO}/include")
set(gtest_GTest_gmock_LIB_DIRS_RELWITHDEBINFO "${gtest_PACKAGE_FOLDER_RELWITHDEBINFO}/lib")
set(gtest_GTest_gmock_BIN_DIRS_RELWITHDEBINFO )
set(gtest_GTest_gmock_LIBRARY_TYPE_RELWITHDEBINFO STATIC)
set(gtest_GTest_gmock_IS_HOST_WINDOWS_RELWITHDEBINFO 0)
set(gtest_GTest_gmock_RES_DIRS_RELWITHDEBINFO )
set(gtest_GTest_gmock_DEFINITIONS_RELWITHDEBINFO )
set(gtest_GTest_gmock_OBJECTS_RELWITHDEBINFO )
set(gtest_GTest_gmock_COMPILE_DEFINITIONS_RELWITHDEBINFO )
set(gtest_GTest_gmock_COMPILE_OPTIONS_C_RELWITHDEBINFO "")
set(gtest_GTest_gmock_COMPILE_OPTIONS_CXX_RELWITHDEBINFO "")
set(gtest_GTest_gmock_LIBS_RELWITHDEBINFO gmock)
set(gtest_GTest_gmock_SYSTEM_LIBS_RELWITHDEBINFO )
set(gtest_GTest_gmock_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(gtest_GTest_gmock_FRAMEWORKS_RELWITHDEBINFO )
set(gtest_GTest_gmock_DEPENDENCIES_RELWITHDEBINFO GTest::gtest)
set(gtest_GTest_gmock_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(gtest_GTest_gmock_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(gtest_GTest_gmock_NO_SONAME_MODE_RELWITHDEBINFO FALSE)

# COMPOUND VARIABLES
set(gtest_GTest_gmock_LINKER_FLAGS_RELWITHDEBINFO
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${gtest_GTest_gmock_SHARED_LINK_FLAGS_RELWITHDEBINFO}>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${gtest_GTest_gmock_SHARED_LINK_FLAGS_RELWITHDEBINFO}>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${gtest_GTest_gmock_EXE_LINK_FLAGS_RELWITHDEBINFO}>
)
set(gtest_GTest_gmock_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${gtest_GTest_gmock_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${gtest_GTest_gmock_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")
########### COMPONENT GTest::gtest_main VARIABLES ############################################

set(gtest_GTest_gtest_main_INCLUDE_DIRS_RELWITHDEBINFO "${gtest_PACKAGE_FOLDER_RELWITHDEBINFO}/include")
set(gtest_GTest_gtest_main_LIB_DIRS_RELWITHDEBINFO "${gtest_PACKAGE_FOLDER_RELWITHDEBINFO}/lib")
set(gtest_GTest_gtest_main_BIN_DIRS_RELWITHDEBINFO )
set(gtest_GTest_gtest_main_LIBRARY_TYPE_RELWITHDEBINFO STATIC)
set(gtest_GTest_gtest_main_IS_HOST_WINDOWS_RELWITHDEBINFO 0)
set(gtest_GTest_gtest_main_RES_DIRS_RELWITHDEBINFO )
set(gtest_GTest_gtest_main_DEFINITIONS_RELWITHDEBINFO )
set(gtest_GTest_gtest_main_OBJECTS_RELWITHDEBINFO )
set(gtest_GTest_gtest_main_COMPILE_DEFINITIONS_RELWITHDEBINFO )
set(gtest_GTest_gtest_main_COMPILE_OPTIONS_C_RELWITHDEBINFO "")
set(gtest_GTest_gtest_main_COMPILE_OPTIONS_CXX_RELWITHDEBINFO "")
set(gtest_GTest_gtest_main_LIBS_RELWITHDEBINFO gtest_main)
set(gtest_GTest_gtest_main_SYSTEM_LIBS_RELWITHDEBINFO )
set(gtest_GTest_gtest_main_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(gtest_GTest_gtest_main_FRAMEWORKS_RELWITHDEBINFO )
set(gtest_GTest_gtest_main_DEPENDENCIES_RELWITHDEBINFO GTest::gtest)
set(gtest_GTest_gtest_main_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(gtest_GTest_gtest_main_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(gtest_GTest_gtest_main_NO_SONAME_MODE_RELWITHDEBINFO FALSE)

# COMPOUND VARIABLES
set(gtest_GTest_gtest_main_LINKER_FLAGS_RELWITHDEBINFO
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${gtest_GTest_gtest_main_SHARED_LINK_FLAGS_RELWITHDEBINFO}>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${gtest_GTest_gtest_main_SHARED_LINK_FLAGS_RELWITHDEBINFO}>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${gtest_GTest_gtest_main_EXE_LINK_FLAGS_RELWITHDEBINFO}>
)
set(gtest_GTest_gtest_main_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${gtest_GTest_gtest_main_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${gtest_GTest_gtest_main_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")
########### COMPONENT GTest::gtest VARIABLES ############################################

set(gtest_GTest_gtest_INCLUDE_DIRS_RELWITHDEBINFO "${gtest_PACKAGE_FOLDER_RELWITHDEBINFO}/include")
set(gtest_GTest_gtest_LIB_DIRS_RELWITHDEBINFO "${gtest_PACKAGE_FOLDER_RELWITHDEBINFO}/lib")
set(gtest_GTest_gtest_BIN_DIRS_RELWITHDEBINFO )
set(gtest_GTest_gtest_LIBRARY_TYPE_RELWITHDEBINFO STATIC)
set(gtest_GTest_gtest_IS_HOST_WINDOWS_RELWITHDEBINFO 0)
set(gtest_GTest_gtest_RES_DIRS_RELWITHDEBINFO )
set(gtest_GTest_gtest_DEFINITIONS_RELWITHDEBINFO )
set(gtest_GTest_gtest_OBJECTS_RELWITHDEBINFO )
set(gtest_GTest_gtest_COMPILE_DEFINITIONS_RELWITHDEBINFO )
set(gtest_GTest_gtest_COMPILE_OPTIONS_C_RELWITHDEBINFO "")
set(gtest_GTest_gtest_COMPILE_OPTIONS_CXX_RELWITHDEBINFO "")
set(gtest_GTest_gtest_LIBS_RELWITHDEBINFO gtest)
set(gtest_GTest_gtest_SYSTEM_LIBS_RELWITHDEBINFO )
set(gtest_GTest_gtest_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(gtest_GTest_gtest_FRAMEWORKS_RELWITHDEBINFO )
set(gtest_GTest_gtest_DEPENDENCIES_RELWITHDEBINFO )
set(gtest_GTest_gtest_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(gtest_GTest_gtest_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(gtest_GTest_gtest_NO_SONAME_MODE_RELWITHDEBINFO FALSE)

# COMPOUND VARIABLES
set(gtest_GTest_gtest_LINKER_FLAGS_RELWITHDEBINFO
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${gtest_GTest_gtest_SHARED_LINK_FLAGS_RELWITHDEBINFO}>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${gtest_GTest_gtest_SHARED_LINK_FLAGS_RELWITHDEBINFO}>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${gtest_GTest_gtest_EXE_LINK_FLAGS_RELWITHDEBINFO}>
)
set(gtest_GTest_gtest_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${gtest_GTest_gtest_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${gtest_GTest_gtest_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")