########### AGGREGATED COMPONENTS AND DEPENDENCIES FOR THE MULTI CONFIG #####################
#############################################################################################

list(APPEND md4c_COMPONENT_NAMES md4c::md4c md4c::md4c-html)
list(REMOVE_DUPLICATES md4c_COMPONENT_NAMES)
if(DEFINED md4c_FIND_DEPENDENCY_NAMES)
  list(APPEND md4c_FIND_DEPENDENCY_NAMES )
  list(REMOVE_DUPLICATES md4c_FIND_DEPENDENCY_NAMES)
else()
  set(md4c_FIND_DEPENDENCY_NAMES )
endif()

########### VARIABLES #######################################################################
#############################################################################################
set(md4c_PACKAGE_FOLDER_RELWITHDEBINFO "/Users/andreas/.conan2/p/b/md4c0a60c9bc55651/p")
set(md4c_BUILD_MODULES_PATHS_RELWITHDEBINFO )


set(md4c_INCLUDE_DIRS_RELWITHDEBINFO "${md4c_PACKAGE_FOLDER_RELWITHDEBINFO}/include")
set(md4c_RES_DIRS_RELWITHDEBINFO )
set(md4c_DEFINITIONS_RELWITHDEBINFO )
set(md4c_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(md4c_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(md4c_OBJECTS_RELWITHDEBINFO )
set(md4c_COMPILE_DEFINITIONS_RELWITHDEBINFO )
set(md4c_COMPILE_OPTIONS_C_RELWITHDEBINFO )
set(md4c_COMPILE_OPTIONS_CXX_RELWITHDEBINFO )
set(md4c_LIB_DIRS_RELWITHDEBINFO "${md4c_PACKAGE_FOLDER_RELWITHDEBINFO}/lib")
set(md4c_BIN_DIRS_RELWITHDEBINFO )
set(md4c_LIBRARY_TYPE_RELWITHDEBINFO STATIC)
set(md4c_IS_HOST_WINDOWS_RELWITHDEBINFO 0)
set(md4c_LIBS_RELWITHDEBINFO md4c-html md4c)
set(md4c_SYSTEM_LIBS_RELWITHDEBINFO )
set(md4c_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(md4c_FRAMEWORKS_RELWITHDEBINFO )
set(md4c_BUILD_DIRS_RELWITHDEBINFO )
set(md4c_NO_SONAME_MODE_RELWITHDEBINFO FALSE)


# COMPOUND VARIABLES
set(md4c_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${md4c_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${md4c_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")
set(md4c_LINKER_FLAGS_RELWITHDEBINFO
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${md4c_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${md4c_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${md4c_EXE_LINK_FLAGS_RELWITHDEBINFO}>")


set(md4c_COMPONENTS_RELWITHDEBINFO md4c::md4c md4c::md4c-html)
########### COMPONENT md4c::md4c-html VARIABLES ############################################

set(md4c_md4c_md4c-html_INCLUDE_DIRS_RELWITHDEBINFO "${md4c_PACKAGE_FOLDER_RELWITHDEBINFO}/include")
set(md4c_md4c_md4c-html_LIB_DIRS_RELWITHDEBINFO "${md4c_PACKAGE_FOLDER_RELWITHDEBINFO}/lib")
set(md4c_md4c_md4c-html_BIN_DIRS_RELWITHDEBINFO )
set(md4c_md4c_md4c-html_LIBRARY_TYPE_RELWITHDEBINFO STATIC)
set(md4c_md4c_md4c-html_IS_HOST_WINDOWS_RELWITHDEBINFO 0)
set(md4c_md4c_md4c-html_RES_DIRS_RELWITHDEBINFO )
set(md4c_md4c_md4c-html_DEFINITIONS_RELWITHDEBINFO )
set(md4c_md4c_md4c-html_OBJECTS_RELWITHDEBINFO )
set(md4c_md4c_md4c-html_COMPILE_DEFINITIONS_RELWITHDEBINFO )
set(md4c_md4c_md4c-html_COMPILE_OPTIONS_C_RELWITHDEBINFO "")
set(md4c_md4c_md4c-html_COMPILE_OPTIONS_CXX_RELWITHDEBINFO "")
set(md4c_md4c_md4c-html_LIBS_RELWITHDEBINFO md4c-html)
set(md4c_md4c_md4c-html_SYSTEM_LIBS_RELWITHDEBINFO )
set(md4c_md4c_md4c-html_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(md4c_md4c_md4c-html_FRAMEWORKS_RELWITHDEBINFO )
set(md4c_md4c_md4c-html_DEPENDENCIES_RELWITHDEBINFO md4c::md4c)
set(md4c_md4c_md4c-html_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(md4c_md4c_md4c-html_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(md4c_md4c_md4c-html_NO_SONAME_MODE_RELWITHDEBINFO FALSE)

# COMPOUND VARIABLES
set(md4c_md4c_md4c-html_LINKER_FLAGS_RELWITHDEBINFO
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${md4c_md4c_md4c-html_SHARED_LINK_FLAGS_RELWITHDEBINFO}>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${md4c_md4c_md4c-html_SHARED_LINK_FLAGS_RELWITHDEBINFO}>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${md4c_md4c_md4c-html_EXE_LINK_FLAGS_RELWITHDEBINFO}>
)
set(md4c_md4c_md4c-html_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${md4c_md4c_md4c-html_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${md4c_md4c_md4c-html_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")
########### COMPONENT md4c::md4c VARIABLES ############################################

set(md4c_md4c_md4c_INCLUDE_DIRS_RELWITHDEBINFO "${md4c_PACKAGE_FOLDER_RELWITHDEBINFO}/include")
set(md4c_md4c_md4c_LIB_DIRS_RELWITHDEBINFO "${md4c_PACKAGE_FOLDER_RELWITHDEBINFO}/lib")
set(md4c_md4c_md4c_BIN_DIRS_RELWITHDEBINFO )
set(md4c_md4c_md4c_LIBRARY_TYPE_RELWITHDEBINFO STATIC)
set(md4c_md4c_md4c_IS_HOST_WINDOWS_RELWITHDEBINFO 0)
set(md4c_md4c_md4c_RES_DIRS_RELWITHDEBINFO )
set(md4c_md4c_md4c_DEFINITIONS_RELWITHDEBINFO )
set(md4c_md4c_md4c_OBJECTS_RELWITHDEBINFO )
set(md4c_md4c_md4c_COMPILE_DEFINITIONS_RELWITHDEBINFO )
set(md4c_md4c_md4c_COMPILE_OPTIONS_C_RELWITHDEBINFO "")
set(md4c_md4c_md4c_COMPILE_OPTIONS_CXX_RELWITHDEBINFO "")
set(md4c_md4c_md4c_LIBS_RELWITHDEBINFO md4c)
set(md4c_md4c_md4c_SYSTEM_LIBS_RELWITHDEBINFO )
set(md4c_md4c_md4c_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(md4c_md4c_md4c_FRAMEWORKS_RELWITHDEBINFO )
set(md4c_md4c_md4c_DEPENDENCIES_RELWITHDEBINFO )
set(md4c_md4c_md4c_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(md4c_md4c_md4c_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(md4c_md4c_md4c_NO_SONAME_MODE_RELWITHDEBINFO FALSE)

# COMPOUND VARIABLES
set(md4c_md4c_md4c_LINKER_FLAGS_RELWITHDEBINFO
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${md4c_md4c_md4c_SHARED_LINK_FLAGS_RELWITHDEBINFO}>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${md4c_md4c_md4c_SHARED_LINK_FLAGS_RELWITHDEBINFO}>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${md4c_md4c_md4c_EXE_LINK_FLAGS_RELWITHDEBINFO}>
)
set(md4c_md4c_md4c_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${md4c_md4c_md4c_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${md4c_md4c_md4c_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")