########### AGGREGATED COMPONENTS AND DEPENDENCIES FOR THE MULTI CONFIG #####################
#############################################################################################

set(miniz_COMPONENT_NAMES "")
if(DEFINED miniz_FIND_DEPENDENCY_NAMES)
  list(APPEND miniz_FIND_DEPENDENCY_NAMES )
  list(REMOVE_DUPLICATES miniz_FIND_DEPENDENCY_NAMES)
else()
  set(miniz_FIND_DEPENDENCY_NAMES )
endif()

########### VARIABLES #######################################################################
#############################################################################################
set(miniz_PACKAGE_FOLDER_RELWITHDEBINFO "/Users/andreas/.conan2/p/b/miniz5c80580ddaacd/p")
set(miniz_BUILD_MODULES_PATHS_RELWITHDEBINFO )


set(miniz_INCLUDE_DIRS_RELWITHDEBINFO "${miniz_PACKAGE_FOLDER_RELWITHDEBINFO}/include"
			"${miniz_PACKAGE_FOLDER_RELWITHDEBINFO}/include/miniz")
set(miniz_RES_DIRS_RELWITHDEBINFO )
set(miniz_DEFINITIONS_RELWITHDEBINFO )
set(miniz_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(miniz_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(miniz_OBJECTS_RELWITHDEBINFO )
set(miniz_COMPILE_DEFINITIONS_RELWITHDEBINFO )
set(miniz_COMPILE_OPTIONS_C_RELWITHDEBINFO )
set(miniz_COMPILE_OPTIONS_CXX_RELWITHDEBINFO )
set(miniz_LIB_DIRS_RELWITHDEBINFO "${miniz_PACKAGE_FOLDER_RELWITHDEBINFO}/lib")
set(miniz_BIN_DIRS_RELWITHDEBINFO )
set(miniz_LIBRARY_TYPE_RELWITHDEBINFO STATIC)
set(miniz_IS_HOST_WINDOWS_RELWITHDEBINFO 0)
set(miniz_LIBS_RELWITHDEBINFO miniz)
set(miniz_SYSTEM_LIBS_RELWITHDEBINFO )
set(miniz_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(miniz_FRAMEWORKS_RELWITHDEBINFO )
set(miniz_BUILD_DIRS_RELWITHDEBINFO )
set(miniz_NO_SONAME_MODE_RELWITHDEBINFO FALSE)


# COMPOUND VARIABLES
set(miniz_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${miniz_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${miniz_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")
set(miniz_LINKER_FLAGS_RELWITHDEBINFO
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${miniz_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${miniz_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${miniz_EXE_LINK_FLAGS_RELWITHDEBINFO}>")


set(miniz_COMPONENTS_RELWITHDEBINFO )