########### AGGREGATED COMPONENTS AND DEPENDENCIES FOR THE MULTI CONFIG #####################
#############################################################################################

set(pugixml_COMPONENT_NAMES "")
if(DEFINED pugixml_FIND_DEPENDENCY_NAMES)
  list(APPEND pugixml_FIND_DEPENDENCY_NAMES )
  list(REMOVE_DUPLICATES pugixml_FIND_DEPENDENCY_NAMES)
else()
  set(pugixml_FIND_DEPENDENCY_NAMES )
endif()

########### VARIABLES #######################################################################
#############################################################################################
set(pugixml_PACKAGE_FOLDER_RELWITHDEBINFO "/Users/andreas/.conan2/p/pugix676f7d1fa98b4/p")
set(pugixml_BUILD_MODULES_PATHS_RELWITHDEBINFO )


set(pugixml_INCLUDE_DIRS_RELWITHDEBINFO "${pugixml_PACKAGE_FOLDER_RELWITHDEBINFO}/include")
set(pugixml_RES_DIRS_RELWITHDEBINFO )
set(pugixml_DEFINITIONS_RELWITHDEBINFO "-DPUGIXML_HEADER_ONLY")
set(pugixml_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(pugixml_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(pugixml_OBJECTS_RELWITHDEBINFO )
set(pugixml_COMPILE_DEFINITIONS_RELWITHDEBINFO "PUGIXML_HEADER_ONLY")
set(pugixml_COMPILE_OPTIONS_C_RELWITHDEBINFO )
set(pugixml_COMPILE_OPTIONS_CXX_RELWITHDEBINFO )
set(pugixml_LIB_DIRS_RELWITHDEBINFO )
set(pugixml_BIN_DIRS_RELWITHDEBINFO )
set(pugixml_LIBRARY_TYPE_RELWITHDEBINFO UNKNOWN)
set(pugixml_IS_HOST_WINDOWS_RELWITHDEBINFO 0)
set(pugixml_LIBS_RELWITHDEBINFO )
set(pugixml_SYSTEM_LIBS_RELWITHDEBINFO )
set(pugixml_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(pugixml_FRAMEWORKS_RELWITHDEBINFO )
set(pugixml_BUILD_DIRS_RELWITHDEBINFO )
set(pugixml_NO_SONAME_MODE_RELWITHDEBINFO FALSE)


# COMPOUND VARIABLES
set(pugixml_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${pugixml_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${pugixml_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")
set(pugixml_LINKER_FLAGS_RELWITHDEBINFO
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${pugixml_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${pugixml_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${pugixml_EXE_LINK_FLAGS_RELWITHDEBINFO}>")


set(pugixml_COMPONENTS_RELWITHDEBINFO )