########### AGGREGATED COMPONENTS AND DEPENDENCIES FOR THE MULTI CONFIG #####################
#############################################################################################

set(utfcpp_COMPONENT_NAMES "")
if(DEFINED utfcpp_FIND_DEPENDENCY_NAMES)
  list(APPEND utfcpp_FIND_DEPENDENCY_NAMES )
  list(REMOVE_DUPLICATES utfcpp_FIND_DEPENDENCY_NAMES)
else()
  set(utfcpp_FIND_DEPENDENCY_NAMES )
endif()

########### VARIABLES #######################################################################
#############################################################################################
set(utfcpp_PACKAGE_FOLDER_RELWITHDEBINFO "/Users/andreas/.conan2/p/utfcp412baeeda02ec/p")
set(utfcpp_BUILD_MODULES_PATHS_RELWITHDEBINFO )


set(utfcpp_INCLUDE_DIRS_RELWITHDEBINFO "${utfcpp_PACKAGE_FOLDER_RELWITHDEBINFO}/include"
			"${utfcpp_PACKAGE_FOLDER_RELWITHDEBINFO}/include/utf8cpp")
set(utfcpp_RES_DIRS_RELWITHDEBINFO )
set(utfcpp_DEFINITIONS_RELWITHDEBINFO )
set(utfcpp_SHARED_LINK_FLAGS_RELWITHDEBINFO )
set(utfcpp_EXE_LINK_FLAGS_RELWITHDEBINFO )
set(utfcpp_OBJECTS_RELWITHDEBINFO )
set(utfcpp_COMPILE_DEFINITIONS_RELWITHDEBINFO )
set(utfcpp_COMPILE_OPTIONS_C_RELWITHDEBINFO )
set(utfcpp_COMPILE_OPTIONS_CXX_RELWITHDEBINFO )
set(utfcpp_LIB_DIRS_RELWITHDEBINFO )
set(utfcpp_BIN_DIRS_RELWITHDEBINFO )
set(utfcpp_LIBRARY_TYPE_RELWITHDEBINFO UNKNOWN)
set(utfcpp_IS_HOST_WINDOWS_RELWITHDEBINFO 0)
set(utfcpp_LIBS_RELWITHDEBINFO )
set(utfcpp_SYSTEM_LIBS_RELWITHDEBINFO )
set(utfcpp_FRAMEWORK_DIRS_RELWITHDEBINFO )
set(utfcpp_FRAMEWORKS_RELWITHDEBINFO )
set(utfcpp_BUILD_DIRS_RELWITHDEBINFO )
set(utfcpp_NO_SONAME_MODE_RELWITHDEBINFO FALSE)


# COMPOUND VARIABLES
set(utfcpp_COMPILE_OPTIONS_RELWITHDEBINFO
    "$<$<COMPILE_LANGUAGE:CXX>:${utfcpp_COMPILE_OPTIONS_CXX_RELWITHDEBINFO}>"
    "$<$<COMPILE_LANGUAGE:C>:${utfcpp_COMPILE_OPTIONS_C_RELWITHDEBINFO}>")
set(utfcpp_LINKER_FLAGS_RELWITHDEBINFO
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${utfcpp_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${utfcpp_SHARED_LINK_FLAGS_RELWITHDEBINFO}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${utfcpp_EXE_LINK_FLAGS_RELWITHDEBINFO}>")


set(utfcpp_COMPONENTS_RELWITHDEBINFO )