#ifndef ODR_EXPERIMENTAL_DOCUMENT_TYPE_H
#define ODR_EXPERIMENTAL_DOCUMENT_TYPE_H

namespace odr::experimental {

enum class DocumentType {
  UNKNOWN,
  TEXT,
  PRESENTATION,
  SPREADSHEET,
  DRAWING,
};

}

#endif // ODR_EXPERIMENTAL_DOCUMENT_TYPE_H
