#!/usr/bin/env python3
"""Generates the single-byte decoding tables in `internal/encoding`.

Each supported single-byte encoding becomes a 256-entry byte -> code point
table. The mappings come from Python's own codecs, which carry the standard
data; codes the encoding leaves undefined become U+FFFD.

The set mirrors the WHATWG Encoding Standard's single-byte encodings, i.e. what
browsers implement, plus a true ISO-8859-1 (WHATWG deliberately folds that one
into windows-1252; we do not, because we report what we detected).

Regenerate with:

    python3 tools/encoding/generate_encoding_data.py
"""

from __future__ import annotations

import pathlib
import sys

REPLACEMENT = 0xFFFD

# (identifier in the generated code, Python codec name)
ENCODINGS = [
    ("ibm866", "cp866"),
    ("iso_8859_1", "iso8859_1"),
    ("iso_8859_2", "iso8859_2"),
    ("iso_8859_3", "iso8859_3"),
    ("iso_8859_4", "iso8859_4"),
    ("iso_8859_5", "iso8859_5"),
    ("iso_8859_6", "iso8859_6"),
    ("iso_8859_7", "iso8859_7"),
    ("iso_8859_8", "iso8859_8"),
    ("iso_8859_10", "iso8859_10"),
    ("iso_8859_13", "iso8859_13"),
    ("iso_8859_14", "iso8859_14"),
    ("iso_8859_15", "iso8859_15"),
    ("iso_8859_16", "iso8859_16"),
    ("koi8_r", "koi8_r"),
    ("koi8_u", "koi8_u"),
    ("macintosh", "mac_roman"),
    ("windows_874", "cp874"),
    ("windows_1250", "cp1250"),
    ("windows_1251", "cp1251"),
    ("windows_1252", "cp1252"),
    ("windows_1253", "cp1253"),
    ("windows_1254", "cp1254"),
    ("windows_1255", "cp1255"),
    ("windows_1256", "cp1256"),
    ("windows_1257", "cp1257"),
    ("windows_1258", "cp1258"),
    ("x_mac_cyrillic", "mac_cyrillic"),
]

HEADER_NOTE = """// Auto-generated by tools/encoding/generate_encoding_data.py -- DO NOT EDIT.
// Regenerate with: python3 tools/encoding/generate_encoding_data.py
// Data: the Python standard library's codecs.

// clang-format off
"""


def table_for(codec: str) -> list[int]:
    result = []
    for byte in range(256):
        try:
            decoded = bytes([byte]).decode(codec)
        except UnicodeDecodeError:
            result.append(REPLACEMENT)
            continue
        # a few codecs map one byte to a combining sequence; none of ours do,
        # and silently truncating would be a wrong table
        if len(decoded) != 1:
            raise ValueError(f"{codec}: byte {byte:#04x} decodes to {decoded!r}")
        result.append(ord(decoded))
    return result


def write_header(path: pathlib.Path) -> None:
    lines = [
        HEADER_NOTE,
        "#pragma once",
        "",
        "#include <array>",
        "",
        "namespace odr::internal::encoding::encoding_data {",
        "",
        "/// Byte -> code point for one single-byte encoding; U+FFFD where the",
        "/// encoding leaves the byte undefined.",
        "using SingleByteTable = std::array<char32_t, 256>;",
        "",
    ]
    lines += [f"extern const SingleByteTable {name};" for name, _ in ENCODINGS]
    lines += ["", "} // namespace odr::internal::encoding::encoding_data", ""]
    path.write_text("\n".join(lines))


def write_source(path: pathlib.Path) -> None:
    lines = [
        HEADER_NOTE,
        "#include <odr/internal/encoding/encoding_data.hpp>",
        "",
        "namespace odr::internal::encoding::encoding_data {",
        "",
    ]
    for name, codec in ENCODINGS:
        table = table_for(codec)
        lines.append(f"const SingleByteTable {name}{{")
        for start in range(0, 256, 8):
            row = ", ".join(f"0x{cp:04x}" for cp in table[start : start + 8])
            lines.append(f"    {row},")
        lines.append("};")
        lines.append("")
    lines += ["} // namespace odr::internal::encoding::encoding_data", ""]
    path.write_text("\n".join(lines))


def main() -> int:
    root = pathlib.Path(__file__).resolve().parents[2]
    out = root / "src" / "odr" / "internal" / "encoding"
    out.mkdir(parents=True, exist_ok=True)
    write_header(out / "encoding_data.hpp")
    write_source(out / "encoding_data.cpp")
    print(f"wrote {len(ENCODINGS)} tables to {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
