package app.opendocument.core;

/** Mirrors {@code odr::FileType}; constant order must match the C++ declaration. */
public enum FileType {
  UNKNOWN, OPENDOCUMENT_TEXT, OPENDOCUMENT_PRESENTATION,
  OPENDOCUMENT_SPREADSHEET, OPENDOCUMENT_GRAPHICS, OFFICE_OPEN_XML_DOCUMENT,
  OFFICE_OPEN_XML_PRESENTATION, OFFICE_OPEN_XML_WORKBOOK,
  OFFICE_OPEN_XML_ENCRYPTED, EXCEL_BINARY_WORKBOOK, LEGACY_WORD_DOCUMENT,
  LEGACY_POWERPOINT_PRESENTATION, LEGACY_EXCEL_WORKSHEETS, WORD_PERFECT,
  RICH_TEXT_FORMAT, PORTABLE_DOCUMENT_FORMAT, TEXT_FILE,
  COMMA_SEPARATED_VALUES, JAVASCRIPT_OBJECT_NOTATION, MARKDOWN, ZIP,
  COMPOUND_FILE_BINARY_FORMAT, PORTABLE_NETWORK_GRAPHICS,
  GRAPHICS_INTERCHANGE_FORMAT, JPEG, BITMAP_IMAGE_FILE, STARVIEW_METAFILE,
  TRUETYPE_FONT, OPENTYPE_FONT;

  static FileType fromNative(int code) {
    return code < 0 ? null : values()[code];
  }

  int toNative() {
    return ordinal();
  }
}
