#ifndef ODR_INTERNAL_FILE_TYPES_H
#define ODR_INTERNAL_FILE_TYPES_H

namespace odr::internal {

enum class FileType {
  UNKNOWN,

  OPENDOCUMENT_TEXT,
  OPENDOCUMENT_PRESENTATION,
  OPENDOCUMENT_SPREADSHEET,
  OPENDOCUMENT_GRAPHICS,

  OFFICE_OPEN_XML_DOCUMENT,
  OFFICE_OPEN_XML_PRESENTATION,
  OFFICE_OPEN_XML_WORKBOOK,
  OFFICE_OPEN_XML_ENCRYPTED,

  LEGACY_WORD_DOCUMENT,
  LEGACY_POWERPOINT_PRESENTATION,
  LEGACY_EXCEL_WORKSHEETS,

  RICH_TEXT_FORMAT,

  PORTABLE_DOCUMENT_FORMAT,

  TEXT_FILE,
  COMMA_SEPARATED_VALUES,
  MARKDOWN,

  ZIP,
  COMPOUND_FILE_BINARY_FORMAT,

  STARVIEW_METAFILE,
};

}

#endif // ODR_INTERNAL_FILE_TYPES_H
