#pragma once

#include <cstdint>
#include <optional>
#include <string>
#include <string_view>

namespace odr::internal::pdf {

/// Translate a string of character codes through a *predefined* Type0 CMap
/// (a composite font's `/Encoding` named in the PDF, e.g. `UniGB-UCS2-H` or
/// `90ms-RKSJ-H`), returning the UTF-8 text; `nullopt` when `name` is not a
/// CMap this module knows.
///
/// Two families are handled:
///  * the predefined **Unicode** CMaps — `Uni*-UCS2`, `-UTF16`, `-UTF32` —
///    whose character codes already *are* Unicode (big-endian), decoded
///    directly with no data tables;
///  * the **legacy CJK** CMaps (RKSJ/EUC/Big5/GBK/KSC and friends), whose codes
///    map to CIDs and then to Unicode via the collection tables in
///    `pdf_cid_data` (generated by `tools/pdf/generate_cid_data.py`). The named
///    CMap declares the codespace (how to split the byte string) and the
///    code -> CID map, and points at its character collection's CID -> Unicode
///    table. A code that maps to no CID, or a CID with no Unicode, contributes
///    nothing (the run may be only partially extractable).
///
/// Returns `nullopt` for `Identity-H/V` (code == CID, no collection implied)
/// and any name not in the tables; the caller then resolves the collection from
/// the descendant CIDFont's `/CIDSystemInfo` via `cid_to_unicode`, or falls
/// back to the embedded font's reverse map, or treats the run as "no Unicode".
[[nodiscard]] std::optional<std::string>
translate_predefined_cmap(std::string_view name, const std::string &codes);

/// Map a single CID to a Unicode code point through a character collection
/// named by the descendant CIDFont's `/CIDSystemInfo` (`registry`/`ordering`,
/// e.g. `Adobe`/`Japan1`). This is the CID -> Unicode half on its own: used
/// when the code -> CID map is already known — `Identity-H/V` (code == CID) or
/// an embedded
/// `/Encoding` CMap stream — so only the collection (from `/CIDSystemInfo`)
/// remains to resolve the text. `nullopt` when the collection is unknown (e.g.
/// the `Identity` ordering, which carries no Unicode meaning) or the CID is
/// unmapped.
[[nodiscard]] std::optional<char32_t> cid_to_unicode(std::string_view registry,
                                                     std::string_view ordering,
                                                     std::uint32_t cid);

} // namespace odr::internal::pdf
