// Auto-generated by tools/pdf/generate_afm_data.py -- DO NOT EDIT.
// Regenerate by rerunning the script; see its header for the source data.
// Adobe Core-14 AFM metrics, redistributed by Apache PDFBox (Apache-2.0);
// see tools/pdf/THIRD_PARTY_LICENSES.md.

// clang-format off

#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <string_view>

namespace odr::internal::pdf::afm_data {

/// One glyph's advance width (glyph space, 1/1000 em), keyed by name.
struct GlyphWidth {
  std::string_view name;
  std::int16_t width;
};

/// One standard-14 font: its name->width table (sorted by name for a
/// binary search), the built-in encoding's code->width table (-1 where
/// the slot is empty), and header metrics (glyph space, 1/1000 em).
struct FontMetrics {
  std::string_view font_name;
  std::int16_t ascender;
  std::int16_t descender;
  std::int16_t cap_height;
  const GlyphWidth *glyphs;
  std::size_t glyph_count;
  const std::int16_t *code_widths; // 256 entries; -1 == absent
};

inline constexpr std::size_t font_count = 14;

extern const std::array<FontMetrics, font_count> fonts;

} // namespace odr::internal::pdf::afm_data
