// Auto-generated by tools/pdf/generate_encoding_data.py — DO NOT EDIT.
// Regenerate with the Adobe Glyph List to populate the full tables; see
// the script header and pdf/AGENTS.md (stage 1.2).

#pragma once

#include <array>
#include <cstddef>
#include <string_view>
#include <utility>

namespace odr::internal::pdf::encoding_data {

inline constexpr std::size_t adobe_glyph_list_size = 104;

extern const std::array<std::string_view, 256> standard_encoding;
extern const std::array<std::string_view, 256> win_ansi_encoding;
extern const std::array<std::string_view, 256> mac_roman_encoding;
extern const std::array<std::string_view, 256> pdf_doc_encoding;

// Adobe Glyph List, sorted by glyph name for binary search; the value is
// the UTF-16 sequence the name maps to.
extern const std::array<std::pair<std::string_view, std::u16string_view>,
                        adobe_glyph_list_size>
    adobe_glyph_list;

} // namespace odr::internal::pdf::encoding_data
