// Auto-generated by tools/pdf/generate_cid_data.py -- DO NOT EDIT.
// Regenerate with: python3 tools/pdf/generate_cid_data.py
// Data: adobe-type-tools/cmap-resources (BSD-3-Clause); see
// tools/pdf/THIRD_PARTY_LICENSES.md.

// clang-format off

#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <string_view>

namespace odr::internal::pdf::cid_data {

// A codespace range: a code whose first byte lands in the leading byte of
// [low, high] is `width` bytes wide (big-endian) -- used to split a string into
// codes. Matched on the first byte, as the runtime CMap does (9.7.6.2).
struct CodespaceRange {
  std::uint32_t low;
  std::uint32_t high;
  std::uint8_t width;
};

// A contiguous code -> CID run: code in [code_low, code_low + run_len] maps to
// cid_low + (code - code_low). `width` is the code's byte count. Runs are split
// so run_len fits a byte, and records are interned (many CMaps share them) --
// each PredefinedCMap indexes this pool through `cid_range_pool`.
struct CidRange {
  std::uint32_t code_low;
  std::uint16_t cid_low;
  std::uint8_t run_len;
  std::uint8_t width;
};

// One astral (> U+FFFF) CID -> Unicode value: the dense-value slot carrying the
// 0xffff sentinel, plus its real code point. Sorted by `value_index`.
struct AstralEntry {
  std::uint32_t value_index;
  char32_t codepoint;
};

// A character collection (e.g. Adobe-Japan1): its dense CID -> Unicode map as a
// presence bitmap over [0, max_cid] (LSB-first within each 64-bit word), a rank
// index (popcount of all words before word i), and a value array indexed by
// rank(cid). A value of 0xffff escapes to `astral`.
struct Collection {
  std::string_view registry;
  std::string_view ordering;
  const std::uint64_t *bitmap;
  const std::uint32_t *rank;
  std::uint32_t word_count;
  std::uint32_t max_cid;
  const std::uint16_t *values;
  const AstralEntry *astral;
  std::uint32_t astral_count;
};

// A predefined CMap (code -> CID). `ranges` indexes `cid_range_pool`, sorted by
// (width, code_low) for binary search; `collection` indexes `collections`.
struct PredefinedCMap {
  std::string_view name;
  const CodespaceRange *codespace;
  std::uint32_t codespace_count;
  const std::uint16_t *ranges;
  std::uint32_t range_count;
  std::uint32_t collection;
};

inline constexpr std::size_t collection_count = 7;
inline constexpr std::size_t predefined_cmap_count = 136;
inline constexpr std::size_t cid_range_pool_size = 23207;

extern const std::array<CidRange, cid_range_pool_size> cid_range_pool;
extern const std::array<Collection, collection_count> collections;
// Sorted by `name` for binary search.
extern const std::array<PredefinedCMap, predefined_cmap_count> predefined_cmaps;

} // namespace odr::internal::pdf::cid_data
