// Auto-generated by tools/pdf/generate_encoding_data.py -- DO NOT EDIT.
// Regenerate after editing the vendored data files next to the script;
// see the script header.

// clang-format off

#pragma once

#include <array>
#include <cstddef>
#include <string_view>
#include <utility>

namespace odr::internal::pdf::encoding_data {

inline constexpr std::size_t adobe_glyph_list_size = 4281;

extern const std::array<std::string_view, 256> standard_encoding;
extern const std::array<std::string_view, 256> win_ansi_encoding;
extern const std::array<std::string_view, 256> mac_roman_encoding;

extern const std::array<std::pair<std::string_view, std::u16string_view>,
                        adobe_glyph_list_size>
    adobe_glyph_list;

} // namespace odr::internal::pdf::encoding_data
