// Auto-generated by tools/pdf/generate_encoding_data.py — DO NOT EDIT.
// Regenerate with the Adobe Glyph List to populate the full tables; see
// the script header and pdf/AGENTS.md (stage 1.2).

#include <odr/internal/pdf/pdf_encoding_data.hpp>

namespace odr::internal::pdf::encoding_data {

const std::array<std::string_view, 256> standard_encoding = {{
    "",             // 0x00
    "",             // 0x01
    "",             // 0x02
    "",             // 0x03
    "",             // 0x04
    "",             // 0x05
    "",             // 0x06
    "",             // 0x07
    "",             // 0x08
    "",             // 0x09
    "",             // 0x0A
    "",             // 0x0B
    "",             // 0x0C
    "",             // 0x0D
    "",             // 0x0E
    "",             // 0x0F
    "",             // 0x10
    "",             // 0x11
    "",             // 0x12
    "",             // 0x13
    "",             // 0x14
    "",             // 0x15
    "",             // 0x16
    "",             // 0x17
    "",             // 0x18
    "",             // 0x19
    "",             // 0x1A
    "",             // 0x1B
    "",             // 0x1C
    "",             // 0x1D
    "",             // 0x1E
    "",             // 0x1F
    "space",        // 0x20
    "exclam",       // 0x21
    "quotedbl",     // 0x22
    "numbersign",   // 0x23
    "dollar",       // 0x24
    "percent",      // 0x25
    "ampersand",    // 0x26
    "quoteright",   // 0x27
    "parenleft",    // 0x28
    "parenright",   // 0x29
    "asterisk",     // 0x2A
    "plus",         // 0x2B
    "comma",        // 0x2C
    "hyphen",       // 0x2D
    "period",       // 0x2E
    "slash",        // 0x2F
    "zero",         // 0x30
    "one",          // 0x31
    "two",          // 0x32
    "three",        // 0x33
    "four",         // 0x34
    "five",         // 0x35
    "six",          // 0x36
    "seven",        // 0x37
    "eight",        // 0x38
    "nine",         // 0x39
    "colon",        // 0x3A
    "semicolon",    // 0x3B
    "less",         // 0x3C
    "equal",        // 0x3D
    "greater",      // 0x3E
    "question",     // 0x3F
    "at",           // 0x40
    "A",            // 0x41
    "B",            // 0x42
    "C",            // 0x43
    "D",            // 0x44
    "E",            // 0x45
    "F",            // 0x46
    "G",            // 0x47
    "H",            // 0x48
    "I",            // 0x49
    "J",            // 0x4A
    "K",            // 0x4B
    "L",            // 0x4C
    "M",            // 0x4D
    "N",            // 0x4E
    "O",            // 0x4F
    "P",            // 0x50
    "Q",            // 0x51
    "R",            // 0x52
    "S",            // 0x53
    "T",            // 0x54
    "U",            // 0x55
    "V",            // 0x56
    "W",            // 0x57
    "X",            // 0x58
    "Y",            // 0x59
    "Z",            // 0x5A
    "bracketleft",  // 0x5B
    "backslash",    // 0x5C
    "bracketright", // 0x5D
    "asciicircum",  // 0x5E
    "underscore",   // 0x5F
    "quoteleft",    // 0x60
    "a",            // 0x61
    "b",            // 0x62
    "c",            // 0x63
    "d",            // 0x64
    "e",            // 0x65
    "f",            // 0x66
    "g",            // 0x67
    "h",            // 0x68
    "i",            // 0x69
    "j",            // 0x6A
    "k",            // 0x6B
    "l",            // 0x6C
    "m",            // 0x6D
    "n",            // 0x6E
    "o",            // 0x6F
    "p",            // 0x70
    "q",            // 0x71
    "r",            // 0x72
    "s",            // 0x73
    "t",            // 0x74
    "u",            // 0x75
    "v",            // 0x76
    "w",            // 0x77
    "x",            // 0x78
    "y",            // 0x79
    "z",            // 0x7A
    "braceleft",    // 0x7B
    "bar",          // 0x7C
    "braceright",   // 0x7D
    "asciitilde",   // 0x7E
    "",             // 0x7F
    "",             // 0x80
    "",             // 0x81
    "",             // 0x82
    "",             // 0x83
    "",             // 0x84
    "",             // 0x85
    "",             // 0x86
    "",             // 0x87
    "",             // 0x88
    "",             // 0x89
    "",             // 0x8A
    "",             // 0x8B
    "",             // 0x8C
    "",             // 0x8D
    "",             // 0x8E
    "",             // 0x8F
    "",             // 0x90
    "",             // 0x91
    "",             // 0x92
    "",             // 0x93
    "",             // 0x94
    "",             // 0x95
    "",             // 0x96
    "",             // 0x97
    "",             // 0x98
    "",             // 0x99
    "",             // 0x9A
    "",             // 0x9B
    "",             // 0x9C
    "",             // 0x9D
    "",             // 0x9E
    "",             // 0x9F
    "",             // 0xA0
    "",             // 0xA1
    "",             // 0xA2
    "",             // 0xA3
    "",             // 0xA4
    "",             // 0xA5
    "",             // 0xA6
    "",             // 0xA7
    "",             // 0xA8
    "",             // 0xA9
    "",             // 0xAA
    "",             // 0xAB
    "",             // 0xAC
    "",             // 0xAD
    "",             // 0xAE
    "",             // 0xAF
    "",             // 0xB0
    "",             // 0xB1
    "",             // 0xB2
    "",             // 0xB3
    "",             // 0xB4
    "",             // 0xB5
    "",             // 0xB6
    "",             // 0xB7
    "",             // 0xB8
    "",             // 0xB9
    "",             // 0xBA
    "",             // 0xBB
    "",             // 0xBC
    "",             // 0xBD
    "",             // 0xBE
    "",             // 0xBF
    "",             // 0xC0
    "",             // 0xC1
    "",             // 0xC2
    "",             // 0xC3
    "",             // 0xC4
    "",             // 0xC5
    "",             // 0xC6
    "",             // 0xC7
    "",             // 0xC8
    "",             // 0xC9
    "",             // 0xCA
    "",             // 0xCB
    "",             // 0xCC
    "",             // 0xCD
    "",             // 0xCE
    "",             // 0xCF
    "",             // 0xD0
    "",             // 0xD1
    "",             // 0xD2
    "",             // 0xD3
    "",             // 0xD4
    "",             // 0xD5
    "",             // 0xD6
    "",             // 0xD7
    "",             // 0xD8
    "",             // 0xD9
    "",             // 0xDA
    "",             // 0xDB
    "",             // 0xDC
    "",             // 0xDD
    "",             // 0xDE
    "",             // 0xDF
    "",             // 0xE0
    "",             // 0xE1
    "",             // 0xE2
    "",             // 0xE3
    "",             // 0xE4
    "",             // 0xE5
    "",             // 0xE6
    "",             // 0xE7
    "",             // 0xE8
    "",             // 0xE9
    "",             // 0xEA
    "",             // 0xEB
    "",             // 0xEC
    "",             // 0xED
    "",             // 0xEE
    "",             // 0xEF
    "",             // 0xF0
    "",             // 0xF1
    "",             // 0xF2
    "",             // 0xF3
    "",             // 0xF4
    "",             // 0xF5
    "",             // 0xF6
    "",             // 0xF7
    "",             // 0xF8
    "",             // 0xF9
    "",             // 0xFA
    "",             // 0xFB
    "",             // 0xFC
    "",             // 0xFD
    "",             // 0xFE
    "",             // 0xFF
}};

const std::array<std::string_view, 256> win_ansi_encoding = {{
    "",             // 0x00
    "",             // 0x01
    "",             // 0x02
    "",             // 0x03
    "",             // 0x04
    "",             // 0x05
    "",             // 0x06
    "",             // 0x07
    "",             // 0x08
    "",             // 0x09
    "",             // 0x0A
    "",             // 0x0B
    "",             // 0x0C
    "",             // 0x0D
    "",             // 0x0E
    "",             // 0x0F
    "",             // 0x10
    "",             // 0x11
    "",             // 0x12
    "",             // 0x13
    "",             // 0x14
    "",             // 0x15
    "",             // 0x16
    "",             // 0x17
    "",             // 0x18
    "",             // 0x19
    "",             // 0x1A
    "",             // 0x1B
    "",             // 0x1C
    "",             // 0x1D
    "",             // 0x1E
    "",             // 0x1F
    "space",        // 0x20
    "exclam",       // 0x21
    "quotedbl",     // 0x22
    "numbersign",   // 0x23
    "dollar",       // 0x24
    "percent",      // 0x25
    "ampersand",    // 0x26
    "quotesingle",  // 0x27
    "parenleft",    // 0x28
    "parenright",   // 0x29
    "asterisk",     // 0x2A
    "plus",         // 0x2B
    "comma",        // 0x2C
    "hyphen",       // 0x2D
    "period",       // 0x2E
    "slash",        // 0x2F
    "zero",         // 0x30
    "one",          // 0x31
    "two",          // 0x32
    "three",        // 0x33
    "four",         // 0x34
    "five",         // 0x35
    "six",          // 0x36
    "seven",        // 0x37
    "eight",        // 0x38
    "nine",         // 0x39
    "colon",        // 0x3A
    "semicolon",    // 0x3B
    "less",         // 0x3C
    "equal",        // 0x3D
    "greater",      // 0x3E
    "question",     // 0x3F
    "at",           // 0x40
    "A",            // 0x41
    "B",            // 0x42
    "C",            // 0x43
    "D",            // 0x44
    "E",            // 0x45
    "F",            // 0x46
    "G",            // 0x47
    "H",            // 0x48
    "I",            // 0x49
    "J",            // 0x4A
    "K",            // 0x4B
    "L",            // 0x4C
    "M",            // 0x4D
    "N",            // 0x4E
    "O",            // 0x4F
    "P",            // 0x50
    "Q",            // 0x51
    "R",            // 0x52
    "S",            // 0x53
    "T",            // 0x54
    "U",            // 0x55
    "V",            // 0x56
    "W",            // 0x57
    "X",            // 0x58
    "Y",            // 0x59
    "Z",            // 0x5A
    "bracketleft",  // 0x5B
    "backslash",    // 0x5C
    "bracketright", // 0x5D
    "asciicircum",  // 0x5E
    "underscore",   // 0x5F
    "grave",        // 0x60
    "a",            // 0x61
    "b",            // 0x62
    "c",            // 0x63
    "d",            // 0x64
    "e",            // 0x65
    "f",            // 0x66
    "g",            // 0x67
    "h",            // 0x68
    "i",            // 0x69
    "j",            // 0x6A
    "k",            // 0x6B
    "l",            // 0x6C
    "m",            // 0x6D
    "n",            // 0x6E
    "o",            // 0x6F
    "p",            // 0x70
    "q",            // 0x71
    "r",            // 0x72
    "s",            // 0x73
    "t",            // 0x74
    "u",            // 0x75
    "v",            // 0x76
    "w",            // 0x77
    "x",            // 0x78
    "y",            // 0x79
    "z",            // 0x7A
    "braceleft",    // 0x7B
    "bar",          // 0x7C
    "braceright",   // 0x7D
    "asciitilde",   // 0x7E
    "",             // 0x7F
    "",             // 0x80
    "",             // 0x81
    "",             // 0x82
    "",             // 0x83
    "",             // 0x84
    "",             // 0x85
    "",             // 0x86
    "",             // 0x87
    "",             // 0x88
    "",             // 0x89
    "",             // 0x8A
    "",             // 0x8B
    "",             // 0x8C
    "",             // 0x8D
    "",             // 0x8E
    "",             // 0x8F
    "",             // 0x90
    "",             // 0x91
    "",             // 0x92
    "",             // 0x93
    "",             // 0x94
    "",             // 0x95
    "",             // 0x96
    "",             // 0x97
    "",             // 0x98
    "",             // 0x99
    "",             // 0x9A
    "",             // 0x9B
    "",             // 0x9C
    "",             // 0x9D
    "",             // 0x9E
    "",             // 0x9F
    "",             // 0xA0
    "",             // 0xA1
    "",             // 0xA2
    "",             // 0xA3
    "",             // 0xA4
    "",             // 0xA5
    "",             // 0xA6
    "",             // 0xA7
    "",             // 0xA8
    "copyright",    // 0xA9
    "",             // 0xAA
    "",             // 0xAB
    "",             // 0xAC
    "",             // 0xAD
    "registered",   // 0xAE
    "",             // 0xAF
    "",             // 0xB0
    "",             // 0xB1
    "",             // 0xB2
    "",             // 0xB3
    "",             // 0xB4
    "",             // 0xB5
    "",             // 0xB6
    "",             // 0xB7
    "",             // 0xB8
    "",             // 0xB9
    "",             // 0xBA
    "",             // 0xBB
    "",             // 0xBC
    "",             // 0xBD
    "",             // 0xBE
    "",             // 0xBF
    "",             // 0xC0
    "",             // 0xC1
    "",             // 0xC2
    "",             // 0xC3
    "",             // 0xC4
    "",             // 0xC5
    "",             // 0xC6
    "",             // 0xC7
    "",             // 0xC8
    "",             // 0xC9
    "",             // 0xCA
    "",             // 0xCB
    "",             // 0xCC
    "",             // 0xCD
    "",             // 0xCE
    "",             // 0xCF
    "",             // 0xD0
    "",             // 0xD1
    "",             // 0xD2
    "",             // 0xD3
    "",             // 0xD4
    "",             // 0xD5
    "",             // 0xD6
    "",             // 0xD7
    "",             // 0xD8
    "",             // 0xD9
    "",             // 0xDA
    "",             // 0xDB
    "",             // 0xDC
    "",             // 0xDD
    "",             // 0xDE
    "",             // 0xDF
    "",             // 0xE0
    "",             // 0xE1
    "",             // 0xE2
    "",             // 0xE3
    "",             // 0xE4
    "",             // 0xE5
    "",             // 0xE6
    "",             // 0xE7
    "",             // 0xE8
    "",             // 0xE9
    "",             // 0xEA
    "",             // 0xEB
    "",             // 0xEC
    "",             // 0xED
    "",             // 0xEE
    "",             // 0xEF
    "",             // 0xF0
    "",             // 0xF1
    "",             // 0xF2
    "",             // 0xF3
    "",             // 0xF4
    "",             // 0xF5
    "",             // 0xF6
    "",             // 0xF7
    "",             // 0xF8
    "",             // 0xF9
    "",             // 0xFA
    "",             // 0xFB
    "",             // 0xFC
    "",             // 0xFD
    "",             // 0xFE
    "",             // 0xFF
}};

const std::array<std::string_view, 256> mac_roman_encoding = {{
    "",             // 0x00
    "",             // 0x01
    "",             // 0x02
    "",             // 0x03
    "",             // 0x04
    "",             // 0x05
    "",             // 0x06
    "",             // 0x07
    "",             // 0x08
    "",             // 0x09
    "",             // 0x0A
    "",             // 0x0B
    "",             // 0x0C
    "",             // 0x0D
    "",             // 0x0E
    "",             // 0x0F
    "",             // 0x10
    "",             // 0x11
    "",             // 0x12
    "",             // 0x13
    "",             // 0x14
    "",             // 0x15
    "",             // 0x16
    "",             // 0x17
    "",             // 0x18
    "",             // 0x19
    "",             // 0x1A
    "",             // 0x1B
    "",             // 0x1C
    "",             // 0x1D
    "",             // 0x1E
    "",             // 0x1F
    "space",        // 0x20
    "exclam",       // 0x21
    "quotedbl",     // 0x22
    "numbersign",   // 0x23
    "dollar",       // 0x24
    "percent",      // 0x25
    "ampersand",    // 0x26
    "quotesingle",  // 0x27
    "parenleft",    // 0x28
    "parenright",   // 0x29
    "asterisk",     // 0x2A
    "plus",         // 0x2B
    "comma",        // 0x2C
    "hyphen",       // 0x2D
    "period",       // 0x2E
    "slash",        // 0x2F
    "zero",         // 0x30
    "one",          // 0x31
    "two",          // 0x32
    "three",        // 0x33
    "four",         // 0x34
    "five",         // 0x35
    "six",          // 0x36
    "seven",        // 0x37
    "eight",        // 0x38
    "nine",         // 0x39
    "colon",        // 0x3A
    "semicolon",    // 0x3B
    "less",         // 0x3C
    "equal",        // 0x3D
    "greater",      // 0x3E
    "question",     // 0x3F
    "at",           // 0x40
    "A",            // 0x41
    "B",            // 0x42
    "C",            // 0x43
    "D",            // 0x44
    "E",            // 0x45
    "F",            // 0x46
    "G",            // 0x47
    "H",            // 0x48
    "I",            // 0x49
    "J",            // 0x4A
    "K",            // 0x4B
    "L",            // 0x4C
    "M",            // 0x4D
    "N",            // 0x4E
    "O",            // 0x4F
    "P",            // 0x50
    "Q",            // 0x51
    "R",            // 0x52
    "S",            // 0x53
    "T",            // 0x54
    "U",            // 0x55
    "V",            // 0x56
    "W",            // 0x57
    "X",            // 0x58
    "Y",            // 0x59
    "Z",            // 0x5A
    "bracketleft",  // 0x5B
    "backslash",    // 0x5C
    "bracketright", // 0x5D
    "asciicircum",  // 0x5E
    "underscore",   // 0x5F
    "grave",        // 0x60
    "a",            // 0x61
    "b",            // 0x62
    "c",            // 0x63
    "d",            // 0x64
    "e",            // 0x65
    "f",            // 0x66
    "g",            // 0x67
    "h",            // 0x68
    "i",            // 0x69
    "j",            // 0x6A
    "k",            // 0x6B
    "l",            // 0x6C
    "m",            // 0x6D
    "n",            // 0x6E
    "o",            // 0x6F
    "p",            // 0x70
    "q",            // 0x71
    "r",            // 0x72
    "s",            // 0x73
    "t",            // 0x74
    "u",            // 0x75
    "v",            // 0x76
    "w",            // 0x77
    "x",            // 0x78
    "y",            // 0x79
    "z",            // 0x7A
    "braceleft",    // 0x7B
    "bar",          // 0x7C
    "braceright",   // 0x7D
    "asciitilde",   // 0x7E
    "",             // 0x7F
    "",             // 0x80
    "",             // 0x81
    "",             // 0x82
    "",             // 0x83
    "",             // 0x84
    "",             // 0x85
    "",             // 0x86
    "",             // 0x87
    "",             // 0x88
    "",             // 0x89
    "",             // 0x8A
    "",             // 0x8B
    "",             // 0x8C
    "",             // 0x8D
    "",             // 0x8E
    "",             // 0x8F
    "",             // 0x90
    "",             // 0x91
    "",             // 0x92
    "",             // 0x93
    "",             // 0x94
    "",             // 0x95
    "",             // 0x96
    "",             // 0x97
    "",             // 0x98
    "",             // 0x99
    "",             // 0x9A
    "",             // 0x9B
    "",             // 0x9C
    "",             // 0x9D
    "",             // 0x9E
    "",             // 0x9F
    "",             // 0xA0
    "",             // 0xA1
    "",             // 0xA2
    "",             // 0xA3
    "",             // 0xA4
    "",             // 0xA5
    "",             // 0xA6
    "",             // 0xA7
    "",             // 0xA8
    "",             // 0xA9
    "",             // 0xAA
    "",             // 0xAB
    "",             // 0xAC
    "",             // 0xAD
    "",             // 0xAE
    "",             // 0xAF
    "",             // 0xB0
    "",             // 0xB1
    "",             // 0xB2
    "",             // 0xB3
    "",             // 0xB4
    "",             // 0xB5
    "",             // 0xB6
    "",             // 0xB7
    "",             // 0xB8
    "",             // 0xB9
    "",             // 0xBA
    "",             // 0xBB
    "",             // 0xBC
    "",             // 0xBD
    "",             // 0xBE
    "",             // 0xBF
    "",             // 0xC0
    "",             // 0xC1
    "",             // 0xC2
    "",             // 0xC3
    "",             // 0xC4
    "",             // 0xC5
    "",             // 0xC6
    "",             // 0xC7
    "",             // 0xC8
    "",             // 0xC9
    "",             // 0xCA
    "",             // 0xCB
    "",             // 0xCC
    "",             // 0xCD
    "",             // 0xCE
    "",             // 0xCF
    "",             // 0xD0
    "",             // 0xD1
    "",             // 0xD2
    "",             // 0xD3
    "",             // 0xD4
    "",             // 0xD5
    "",             // 0xD6
    "",             // 0xD7
    "",             // 0xD8
    "",             // 0xD9
    "",             // 0xDA
    "",             // 0xDB
    "",             // 0xDC
    "",             // 0xDD
    "",             // 0xDE
    "",             // 0xDF
    "",             // 0xE0
    "",             // 0xE1
    "",             // 0xE2
    "",             // 0xE3
    "",             // 0xE4
    "",             // 0xE5
    "",             // 0xE6
    "",             // 0xE7
    "",             // 0xE8
    "",             // 0xE9
    "",             // 0xEA
    "",             // 0xEB
    "",             // 0xEC
    "",             // 0xED
    "",             // 0xEE
    "",             // 0xEF
    "",             // 0xF0
    "",             // 0xF1
    "",             // 0xF2
    "",             // 0xF3
    "",             // 0xF4
    "",             // 0xF5
    "",             // 0xF6
    "",             // 0xF7
    "",             // 0xF8
    "",             // 0xF9
    "",             // 0xFA
    "",             // 0xFB
    "",             // 0xFC
    "",             // 0xFD
    "",             // 0xFE
    "",             // 0xFF
}};

const std::array<std::string_view, 256> pdf_doc_encoding = {{
    "",             // 0x00
    "",             // 0x01
    "",             // 0x02
    "",             // 0x03
    "",             // 0x04
    "",             // 0x05
    "",             // 0x06
    "",             // 0x07
    "",             // 0x08
    "",             // 0x09
    "",             // 0x0A
    "",             // 0x0B
    "",             // 0x0C
    "",             // 0x0D
    "",             // 0x0E
    "",             // 0x0F
    "",             // 0x10
    "",             // 0x11
    "",             // 0x12
    "",             // 0x13
    "",             // 0x14
    "",             // 0x15
    "",             // 0x16
    "",             // 0x17
    "",             // 0x18
    "",             // 0x19
    "",             // 0x1A
    "",             // 0x1B
    "",             // 0x1C
    "",             // 0x1D
    "",             // 0x1E
    "",             // 0x1F
    "space",        // 0x20
    "exclam",       // 0x21
    "quotedbl",     // 0x22
    "numbersign",   // 0x23
    "dollar",       // 0x24
    "percent",      // 0x25
    "ampersand",    // 0x26
    "quotesingle",  // 0x27
    "parenleft",    // 0x28
    "parenright",   // 0x29
    "asterisk",     // 0x2A
    "plus",         // 0x2B
    "comma",        // 0x2C
    "hyphen",       // 0x2D
    "period",       // 0x2E
    "slash",        // 0x2F
    "zero",         // 0x30
    "one",          // 0x31
    "two",          // 0x32
    "three",        // 0x33
    "four",         // 0x34
    "five",         // 0x35
    "six",          // 0x36
    "seven",        // 0x37
    "eight",        // 0x38
    "nine",         // 0x39
    "colon",        // 0x3A
    "semicolon",    // 0x3B
    "less",         // 0x3C
    "equal",        // 0x3D
    "greater",      // 0x3E
    "question",     // 0x3F
    "at",           // 0x40
    "A",            // 0x41
    "B",            // 0x42
    "C",            // 0x43
    "D",            // 0x44
    "E",            // 0x45
    "F",            // 0x46
    "G",            // 0x47
    "H",            // 0x48
    "I",            // 0x49
    "J",            // 0x4A
    "K",            // 0x4B
    "L",            // 0x4C
    "M",            // 0x4D
    "N",            // 0x4E
    "O",            // 0x4F
    "P",            // 0x50
    "Q",            // 0x51
    "R",            // 0x52
    "S",            // 0x53
    "T",            // 0x54
    "U",            // 0x55
    "V",            // 0x56
    "W",            // 0x57
    "X",            // 0x58
    "Y",            // 0x59
    "Z",            // 0x5A
    "bracketleft",  // 0x5B
    "backslash",    // 0x5C
    "bracketright", // 0x5D
    "asciicircum",  // 0x5E
    "underscore",   // 0x5F
    "grave",        // 0x60
    "a",            // 0x61
    "b",            // 0x62
    "c",            // 0x63
    "d",            // 0x64
    "e",            // 0x65
    "f",            // 0x66
    "g",            // 0x67
    "h",            // 0x68
    "i",            // 0x69
    "j",            // 0x6A
    "k",            // 0x6B
    "l",            // 0x6C
    "m",            // 0x6D
    "n",            // 0x6E
    "o",            // 0x6F
    "p",            // 0x70
    "q",            // 0x71
    "r",            // 0x72
    "s",            // 0x73
    "t",            // 0x74
    "u",            // 0x75
    "v",            // 0x76
    "w",            // 0x77
    "x",            // 0x78
    "y",            // 0x79
    "z",            // 0x7A
    "braceleft",    // 0x7B
    "bar",          // 0x7C
    "braceright",   // 0x7D
    "asciitilde",   // 0x7E
    "",             // 0x7F
    "",             // 0x80
    "",             // 0x81
    "",             // 0x82
    "",             // 0x83
    "",             // 0x84
    "",             // 0x85
    "",             // 0x86
    "",             // 0x87
    "",             // 0x88
    "",             // 0x89
    "",             // 0x8A
    "",             // 0x8B
    "",             // 0x8C
    "",             // 0x8D
    "",             // 0x8E
    "",             // 0x8F
    "",             // 0x90
    "",             // 0x91
    "",             // 0x92
    "",             // 0x93
    "",             // 0x94
    "",             // 0x95
    "",             // 0x96
    "",             // 0x97
    "",             // 0x98
    "",             // 0x99
    "",             // 0x9A
    "",             // 0x9B
    "",             // 0x9C
    "",             // 0x9D
    "",             // 0x9E
    "",             // 0x9F
    "",             // 0xA0
    "",             // 0xA1
    "",             // 0xA2
    "",             // 0xA3
    "",             // 0xA4
    "",             // 0xA5
    "",             // 0xA6
    "",             // 0xA7
    "",             // 0xA8
    "copyright",    // 0xA9
    "",             // 0xAA
    "",             // 0xAB
    "",             // 0xAC
    "",             // 0xAD
    "registered",   // 0xAE
    "",             // 0xAF
    "",             // 0xB0
    "",             // 0xB1
    "",             // 0xB2
    "",             // 0xB3
    "",             // 0xB4
    "",             // 0xB5
    "",             // 0xB6
    "",             // 0xB7
    "",             // 0xB8
    "",             // 0xB9
    "",             // 0xBA
    "",             // 0xBB
    "",             // 0xBC
    "",             // 0xBD
    "",             // 0xBE
    "",             // 0xBF
    "",             // 0xC0
    "",             // 0xC1
    "",             // 0xC2
    "",             // 0xC3
    "",             // 0xC4
    "",             // 0xC5
    "",             // 0xC6
    "",             // 0xC7
    "",             // 0xC8
    "",             // 0xC9
    "",             // 0xCA
    "",             // 0xCB
    "",             // 0xCC
    "",             // 0xCD
    "",             // 0xCE
    "",             // 0xCF
    "",             // 0xD0
    "",             // 0xD1
    "",             // 0xD2
    "",             // 0xD3
    "",             // 0xD4
    "",             // 0xD5
    "",             // 0xD6
    "",             // 0xD7
    "",             // 0xD8
    "",             // 0xD9
    "",             // 0xDA
    "",             // 0xDB
    "",             // 0xDC
    "",             // 0xDD
    "",             // 0xDE
    "",             // 0xDF
    "",             // 0xE0
    "",             // 0xE1
    "",             // 0xE2
    "",             // 0xE3
    "",             // 0xE4
    "",             // 0xE5
    "",             // 0xE6
    "",             // 0xE7
    "",             // 0xE8
    "",             // 0xE9
    "",             // 0xEA
    "",             // 0xEB
    "",             // 0xEC
    "",             // 0xED
    "",             // 0xEE
    "",             // 0xEF
    "",             // 0xF0
    "",             // 0xF1
    "",             // 0xF2
    "",             // 0xF3
    "",             // 0xF4
    "",             // 0xF5
    "",             // 0xF6
    "",             // 0xF7
    "",             // 0xF8
    "",             // 0xF9
    "",             // 0xFA
    "",             // 0xFB
    "",             // 0xFC
    "",             // 0xFD
    "",             // 0xFE
    "",             // 0xFF
}};

const std::array<std::pair<std::string_view, std::u16string_view>,
                 adobe_glyph_list_size>
    adobe_glyph_list = {{
        {"A", u"\u0041"},
        {"B", u"\u0042"},
        {"C", u"\u0043"},
        {"D", u"\u0044"},
        {"E", u"\u0045"},
        {"F", u"\u0046"},
        {"G", u"\u0047"},
        {"H", u"\u0048"},
        {"I", u"\u0049"},
        {"J", u"\u004A"},
        {"K", u"\u004B"},
        {"L", u"\u004C"},
        {"M", u"\u004D"},
        {"N", u"\u004E"},
        {"O", u"\u004F"},
        {"P", u"\u0050"},
        {"Q", u"\u0051"},
        {"R", u"\u0052"},
        {"S", u"\u0053"},
        {"T", u"\u0054"},
        {"U", u"\u0055"},
        {"V", u"\u0056"},
        {"W", u"\u0057"},
        {"X", u"\u0058"},
        {"Y", u"\u0059"},
        {"Z", u"\u005A"},
        {"a", u"\u0061"},
        {"ampersand", u"\u0026"},
        {"asciicircum", u"\u005E"},
        {"asciitilde", u"\u007E"},
        {"asterisk", u"\u002A"},
        {"at", u"\u0040"},
        {"b", u"\u0062"},
        {"backslash", u"\u005C"},
        {"bar", u"\u007C"},
        {"braceleft", u"\u007B"},
        {"braceright", u"\u007D"},
        {"bracketleft", u"\u005B"},
        {"bracketright", u"\u005D"},
        {"bullet", u"\u2022"},
        {"c", u"\u0063"},
        {"colon", u"\u003A"},
        {"comma", u"\u002C"},
        {"copyright", u"\u00A9"},
        {"d", u"\u0064"},
        {"dollar", u"\u0024"},
        {"e", u"\u0065"},
        {"eight", u"\u0038"},
        {"emdash", u"\u2014"},
        {"endash", u"\u2013"},
        {"equal", u"\u003D"},
        {"exclam", u"\u0021"},
        {"f", u"\u0066"},
        {"fi", u"\u0066\u0069"},
        {"five", u"\u0035"},
        {"fl", u"\u0066\u006C"},
        {"four", u"\u0034"},
        {"g", u"\u0067"},
        {"grave", u"\u0060"},
        {"greater", u"\u003E"},
        {"h", u"\u0068"},
        {"hyphen", u"\u002D"},
        {"i", u"\u0069"},
        {"j", u"\u006A"},
        {"k", u"\u006B"},
        {"l", u"\u006C"},
        {"less", u"\u003C"},
        {"m", u"\u006D"},
        {"n", u"\u006E"},
        {"nine", u"\u0039"},
        {"numbersign", u"\u0023"},
        {"o", u"\u006F"},
        {"one", u"\u0031"},
        {"p", u"\u0070"},
        {"parenleft", u"\u0028"},
        {"parenright", u"\u0029"},
        {"percent", u"\u0025"},
        {"period", u"\u002E"},
        {"plus", u"\u002B"},
        {"q", u"\u0071"},
        {"question", u"\u003F"},
        {"quotedbl", u"\u0022"},
        {"quoteleft", u"\u2018"},
        {"quoteright", u"\u2019"},
        {"quotesingle", u"\u0027"},
        {"r", u"\u0072"},
        {"registered", u"\u00AE"},
        {"s", u"\u0073"},
        {"semicolon", u"\u003B"},
        {"seven", u"\u0037"},
        {"six", u"\u0036"},
        {"slash", u"\u002F"},
        {"space", u"\u0020"},
        {"t", u"\u0074"},
        {"three", u"\u0033"},
        {"two", u"\u0032"},
        {"u", u"\u0075"},
        {"underscore", u"\u005F"},
        {"v", u"\u0076"},
        {"w", u"\u0077"},
        {"x", u"\u0078"},
        {"y", u"\u0079"},
        {"z", u"\u007A"},
        {"zero", u"\u0030"},
    }};

} // namespace odr::internal::pdf::encoding_data
