#!/usr/bin/env bash

conan install . --output-folder=cmake-build-debug --build=missing -s build_type=Release -s "&:build_type=Debug"
conan install . --output-folder=cmake-build-release --build=missing -s build_type=Release -s "&:build_type=Release"
