#!/usr/bin/env bash

CLANG_FORMAT=${CLANG_FORMAT:-clang-format}

echo "Running clang-format on all .hpp and .cpp files in the project"
echo "Using clang-format: ${CLANG_FORMAT}"

${CLANG_FORMAT} --version

function format() {
    echo "Formatting $1"
    ${CLANG_FORMAT} --style=file -i $1
}
export -f format
export CLANG_FORMAT
find . -type f \( -iname \*.hpp -o -iname \*.cpp \) -exec bash -c 'format "${1}"' -- {} \;
