// Generated by tools/number_format/generate_calendar_names.py; do not edit.
// Regenerate with: python3 tools/number_format/generate_calendar_names.py
// Data: the names LibreOffice renders for each language.

// clang-format off

#pragma once

#include <array>
#include <string_view>

namespace odr::internal::number_format {

/// The names a date shows in one language.
struct CalendarNames final {
  std::string_view language;
  std::array<std::string_view, 12> months;
  /// A month after a day, where the language declines it.
  std::array<std::string_view, 12> months_after_day;
  std::array<std::string_view, 12> short_months;
  /// Sunday first.
  std::array<std::string_view, 7> days;
  std::array<std::string_view, 7> short_days;
};

/// English first.
extern const std::array<CalendarNames, 34> calendar_names;

} // namespace odr::internal::number_format
