name: docker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test_image:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_ANDIWAND }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: test/docker
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}:buildcache,mode=max

      # TODO try to run it
