name: format

on: push

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: apply clang-format
        run: CLANG_FORMAT=clang-format-18 ./scripts/format

      - run: git diff --exit-code --name-only
