name: conan

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: set up python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install python dependencies
        run: pip install --upgrade pip conan==1.*

      - name: conan config
        run: conan config set general.revisions_enabled=1
      - name: conan remote
        run: |
          conan remote clean
          conan remote add conancenter https://center.conan.io
          conan remote add odr https://artifactory.opendocument.app/artifactory/api/conan/conan
      - name: conan login
        run: conan user --remote odr --password ${{ secrets.ARTIFACTORY }} admin

      - name: checkout
        uses: actions/checkout@v2

      - name: get version
        run: echo "VERSION=${GITHUB_REF_NAME:1}" >> $GITHUB_ENV

      - name: create conan package
        run: conan create conanfile.py odrcore/${VERSION}@ -s compiler.libcxx=libstdc++11 --build missing

      - name: upload to conan repo
        run: conan upload "*" --remote odr --confirm --all --no-overwrite all
