name: conan

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-24.04, build_profile: ubuntu-24.04-clang-18, host_profile: ubuntu-24.04-clang-18 }
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set up python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: install python dependencies
        run: pip install --upgrade pip conan

      - name: conan remote
        run: conan remote add odr https://artifactory.opendocument.app/artifactory/api/conan/conan

      - name: conan config
        run: conan config install .github/config/conan

      - name: get version
        run: echo "VERSION=${GITHUB_REF_NAME:1}" >> $GITHUB_ENV

      - name: create conan package
        run: >
          conan create conanfile.py
          --lockfile conan.lock
          --profile:host '${{ matrix.host_profile }}'
          --profile:build '${{ matrix.build_profile }}'
          --name odrcore
          --version ${VERSION}
          --build missing

      - name: conan login
        run: conan remote login odr admin --password ${{ secrets.ARTIFACTORY }}

      - name: upload to conan repo
        run: conan upload "*" --remote odr --confirm
