name: conan

on:
  release:
    types: [published]

env:
  CONAN_ODR_INDEX_REF: 4c017e76b56d6972564bd6d704a8843076b94f32

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-24.04, build_profile: ubuntu-24.04-clang-18, host_profile: ubuntu-24.04-clang-18 }
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set up python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: install python dependencies
        run: pip install --upgrade pip conan

      - name: get version
        run: echo "VERSION=${GITHUB_REF_NAME:1}" >> $GITHUB_ENV

      - name: fetch conan-odr-index
        uses: actions/checkout@v4
        with:
          repository: opendocument-app/conan-odr-index
          ref: ${{ env.CONAN_ODR_INDEX_REF }}
      - name: export conan-odr-index
        run: python conan-odr-index/scripts/conan_export_all_packages.py
      - name: conan config
        run: conan config install .github/config/conan

      - name: conan install
        run: >
          conan install .
          --lockfile conan.lock
          --profile:host '${{ matrix.host_profile }}'
          --profile:build '${{ matrix.build_profile }}'
          --build "*"

      - name: create conan package
        run: >
          conan create .
          --lockfile=conan.lock
          --profile:host '${{ matrix.host_profile }}'
          --profile:build '${{ matrix.build_profile }}'
          --name odrcore
          --version ${VERSION}
          --build "*"

      - name: conan login
        run: conan remote login odr admin --password ${{ secrets.ARTIFACTORY }}

      - name: upload to conan repo
        run: conan upload "*" --remote odr --only-recipe --confirm
