name: conan

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: set up python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install python dependencies
        run: pip install --upgrade pip conan==1.*

      - name: checkout
        uses: actions/checkout@v2

      - run: echo "VERSION=${GITHUB_REF_NAME:1}" >> $GITHUB_ENV

      - run: conan create conanfile.py odrcore/${VERSION}@ -s compiler.libcxx=libstdc++11 --build missing
