name: tidy

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CCACHE_DIR: ${{ github.workspace }}/ccache
  CCACHE_MAXSIZE: 500M
  CCACHE_KEY_SUFFIX: r22
  CONAN_ODR_INDEX_REF: 4c017e76b56d6972564bd6d704a8843076b94f32

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-24.04, build_profile: ubuntu-24.04-clang-18, host_profile: ubuntu-24.04-clang-18 }
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - run: clang-tidy --version

      - name: setup python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: install python dependencies
        run: pip install --upgrade pip conan

      - name: fetch conan-odr-index
        uses: actions/checkout@v4
        with:
          repository: opendocument-app/conan-odr-index
          ref: ${{ env.CONAN_ODR_INDEX_REF }}
      - name: export conan-odr-index
        run: python conan-odr-index/scripts/conan_export_all_packages.py
      - name: conan config
        run: conan config install .github/config/conan

      - name: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.ccache
            /Users/runner/Library/Caches/ccache
          key: ${{ matrix.host_profile }}-${{ env.CCACHE_KEY_SUFFIX }}
          restore-keys: |
            ${{ matrix.host_profile }}-

      - name: conan install
        run: >
          conan install .
          --lockfile conan.lock
          --profile:host '${{ matrix.host_profile }}'
          --profile:build '${{ matrix.build_profile }}'
          --build "*"

      - name: cmake
        run: >
          cmake -S . -B build
          -DCMAKE_TOOLCHAIN_FILE="conan_toolchain.cmake"
          -DCMAKE_BUILD_TYPE=Release
          -DODR_CLANG_TIDY=ON

      - name: clang-tidy
        run: cmake --build build
